name: test_flutter_vlad
description: "A Flutter package with customizable UI components for fast and modern app development."
repository: "https://github.com/vlad-dashkevich-gismart/flutter_test_module.git"
version: 1.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.1
#  connectivity_plus: ^5.0.2
#  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.test_flutter
    iosBundleIdentifier: com.example.testFlutter
